### ISSUE TITLE
Female hurt sound disconnects you from your world.

### ISSUE THREAD

**Issue by Bobeik** [WildfireRomeo/WildfireFemaleGenderMod#76] opened 2022-10-09 17:43 UTC
I was playing Mincraft and when i got hit by an arrow the game disconnected me. I think it has something to do with a minecraft bug fix, or something that made the sound unable to be played properly. Also the game works perfectly fine when i turn of Female hurt sound. Thx.

Image:
![Skjermbilde (27)](https://user-images.githubusercontent.com/113543419/194771488-3c4bfc0b-61dd-480c-b985-62003ac5bb75.png)

**Comment by WildfireRomeo** [comment] 2022-10-09 20:18
Known Issue, Duplicate of #57

**Closed by WildfireRomeo** 2022-10-09 20:18 UTC
