### ISSUE TITLE
crash on load

### ISSUE THREAD

**Issue by VerserVarlin** [WildfireRomeo/WildfireFemaleGenderMod#59] opened 2022-07-18 12:37 UTC
game crashes on load, link to crash report: https://pastebin.com/P95PHLsX

**Comment by Kichura** [comment] 2022-07-20 06:56
Caused by forge 41 as it changed classes again, See #55.

**Comment by WildfireRomeo** [comment] 2022-08-07 16:55
Fixed in latest version

**Closed by WildfireRomeo** 2022-08-07 16:55 UTC
